---
title: Simple principles for engineering reproducible solutions to environmental management challenges.
author:
  - name: Malory Owen
    email: maloryowen@gmail.com
    affiliation: York University
  - name: Christopher J. Lortie
    email: lortie@yorku.ca
    affiliation: Biology, York University
    corresponding: lortie@yorku.ca
address:
  - code: York University
    address: Biology, 4700 Keele St. Toronto, ON, Canada, M3J1P3

abstract: |
  An environmental management challenge is an opportunity to use fundamental science to inform evidence-based decisions for  environmental stakeholders and conservationists.  Contemporary science is embracing open science and increasingly conscious of reproduciblility.  Synergistically, applying these two paradigms in concert advances our capacity to move beyond context dependency and singlular thinking to reverse engineer solutions from published scientific evidence associated with one challenge to many. Herein, we provide a short list of principles that can guide those that seek solutions to address environmental management through primary scientific literature.
  
author_summary: |
  Grand challenges require grand solutions. Environmental management cannot neglect fundamental science as a substrate for effective decision making, and scientists should be conscious of how their science can be used by managers. 

bibliography: mybibfile.bib
output: rticles::plos_article
csl: plos.csl
---

# Introduction

Conservation decisions can reside with legislators (indirect impactors) or environmental managers (direct impactors).  To focus on the latter, managers typically have scientific backgrounds and routinely navigate the technical literature.  However, engagement with scientific literature is non-trivial for all practitioners because of time, access, relevance of the science, and reporting standards.  Environmental managers and conservationist are certainly seeking evidence to inform decisions (citations please). However, there can be a gap in communication between basic science and management for at least three reasons.  Firstly, the research is not a direct study of an ecosystem, and an immediate, real-world solution is needed by managers - preferably with a demonstrable outcome and reasonable cost estimate (citations).  This is a very real limitation in the primary science literature restoration ecology for instance (cite Lortie better late than never). Secondly, the link between the biology or ecology present in the literature is not articulately connected to the similar process for the system at hand. There are notable examples with journals just as the Journal of Applied Ecology, Basic and Applied Ecology, the Journal of Environmental Engineering, and many others, but there nonetheless remains a vast pool of opportunity for solution development in other journals.  Context-specific findings in science are a legimitate and useful means to advance discovery, but at times, studies from one system can be repurposed for insights into another. Finally, the capacity to see the forest for the trees or the generality of a specific, even large-scale or broad basic research study can be a challenge. Science can be very specialized (citation to Nancy Baron book), and mobilizing knowledge for solutions requires both detailed expertise, scientific synthesis tools (cite to Lortie formalized synthesis paper in Oikos), or a focus on identifying the salient elements associated with a study (citation). Often, seeing the forest also requires sampling many trees. This leads to the general proposal here that experts can promote reproducible and mobile knowledge for many fundamental science endeavors by considering these principles. This is both a set of principles for how to make your research potentially reusable by environmental managers and conservationists (citation to get your paper used by meta) and inform solutions for the environmental crisis.


An environmental management challenge is a problem presented in scientific literature or society that, when redefined and reviewed using these 10 principles, can result in a solution to the original problem. EXPAND... a tiny bit more..how. Typically, a challenge is.... look up how they define grand challenges and make mention here including the 17 global sustainability goals. A (reverse-engineered) reproducible solution is a suggested solution to a challenge derived from identifying all the components of the challenge.  It should be applicable to multiple local-extent challenges when tweaked to fit the circumstances. Finally, a tool or solution is the desired outcome from the primary research to support evidence-based decision making in conservation. In this case, a tool is a methodology researchers use that can faciitate managers to either identify best ways to measure/identify issues or to provide solutions for their specific challenge.  Any tool is linked to its respective reproducible solution by the fundamental concepts of reproducibility (citation to reproducibility crisis paper). These can include primarily conceptual replication but also.... check papers on reproducibility. then concluding sentence.

The heuristic developed here was inspired by the "Ten Simple Rules" format pioneered by Phillip Bourne in the field of computational biology [@Bourne2006]. We propose that by distilling the concepts that promote engagement with scientific literature outside of the research community, managers can rely on broader sources of scientific knowledge to make decisions.  Additionally, researchers can better understand the perspective of managers facilitating science and scientific communication that is more applicable to managers without compromising their research programs.  Here, we will outline and discuss simple "principles" scientists can use to make their research more applicable to managers, and managers can use to identify basic science that fits their needs.





# The principles

**1. Reframe the problem as challenge.**
Doom-and-gloom is a pervasive mentality in ecology and environmental sciences which can reduce productivity and problem solving.  It can shut down even the most motivated of minds--but beyond the issue of motivation, reframing a problem as a *challenge* can reveal solution sets that may otherwise remain hidden.  For example, consider the problem of human-wildlife conflict between carnivores and the people living near the Ruaha National Park boundary in Tanzania.  The *problem* is that 98.5% of people perceive wildlife as a threat to their livestock resulting in increased likelihoods for human-wildlife conflict [@Dickman2014].  Reframed, the challenge can be to decrease the negative perception of wildlife in areas with high human-wildlife conflict opportunities.  It is a small change in semantics, but it is a potentially profound change in direction.  

**2. Describe the scope and extent of the challenge.**
Defining the scope of a challenge conceptually and the extent geographically will ensure that potential solutions fit the challenge. Moving across scales is a common issue in ecology (citation to Sandel 2015 paper in Ecography), and proposing a spatial scale, using common terms, and describing the breadth of the challenge will accelerate interdisciplinary solutions (i.e. the wildlife-human challenge above is ecological and societal).  The challenge can be problematic on multiple scales including local, regional, or global scale and solutions can be needed for each.  Conceptually, the scope is broad in the human-wildlife conflict example whilst the extent is primarily local to the area surrounding the Southern border of the Ruaha National Park.

**3. Explicitly link the basic science to management implications and policy.**
Perhaps the most facile principle, a simple description and definition of the basic scientific evidence in a study and how it can be resued is a fundamental step in linking science to evidence-based decision making for environmental challenges. In the wildlife-human challenge, depredation of livestock impacted 61.1% of households, but livestock loss due to disease or theft was X percent? of total loss [@Dickman2014].  Consequently, a clear statement of evidence can illuminate the most viable solution sets in some instances.  

**4. Propose implications of ignoring this challenge.**
A description of the impact a challenge on a system if left unchecked will help clarify the severity of the challenge. The trickle down effects and indirect implications of the challenge should also be examined. For instance, anti-carnivore sentiment will likely only grow as climate change and pressures to confine pastoral herders makes livestock more difficult to raise [@Jones2009; @Lindsey2009].  Many large carnivores are already threatened/endangered, and further anthropogenic pressures on the populations will lead to severe declines in populations including potential extinction of keystone species [@Towns2009; @Bagchi2006; @Johnson2006]; but it is often associated with underlying human-human conflict [@Dickman2010]. 

**5. State the direct human needs associated with this challenge.**
State the direct needs of humans as part of the process of generating reproducible solutions for environmental challenges.  The intrinsic value of the ecosystem is unrefutable (citation) but also linking the challenge and its solutions to direct human needs makes it less likely to be dismissed.  Identifying  anthropogenic needs will help a problem solver create a solution that is appropriate for the challenge, and it can also prevent the emergence of new related challenges or pressures on the system in question. This principle can also include engagement with stakeholders as a mechanism to inform benefits and solutions (citations to colvin and reed papers on github issue).


**6. List at least one limitation of the study and explain.**
There is no perfect experiment (Ruxton citation) or synthesis (Kotiaho & Tomkins citation). Critically reading the study associated with the challenge can mean the difference between success and failure of a later implemented management solution that otherwise follows all other principles presented.  For example, conflating causation with correlation can be a fatal misstep if making real-world decisions based on a correlated trend.  However, it's an unfortunate truth that conservationists and managers often have to make decisions on a real-world challenge without fully understanding the system in which they work, since a solution is often needed immediately in order to prevent a catastrophic loss.  Still, knowing the relative strength of a solution can help prepare for a range of outcomes.  Perhaps the most important step, however, is to identify limitations of the study in order to best advocate for an eventual solution's implementation.  Being well versed in counter-arguments is essential in any debate, and it is no different when advocating for a solution.

**7. Explore the benefits of minimal intervention for stakeholders.**
The culmination of principles of 4, 5, and 6, principle 7 is another idea that can feel uncomfortable to a traditional conservationist.  Why not just do *everything* so that all our bases are covered?  Unfortunately, resources to conserve the environment are limited, and managers must maximize their "profits" (positive restoration/conservation outcomes).  Ideally, a well-designed solution takes minimal resource allocation, and has minimal incidental negative effects. 

**8. List the tools applied to this challenge.**
This principle is most critical for researchers wishing to make their science more amenable to management use, but is also helpful to managers seeking relevant papers beyond studies which focus specifically on their projects.  In an environmental management challenge case study, there is usually one primary tool the researchers use to produce their results. However, there can be many more than one! These tools usually take the form of common methodologies that can be used across sub-disciplines, and are easily identifiable.  Look to the methods to identify these tools.  Some examples of primary tools we have found include:
*meta-analysis [@Castanho2015]; [@Busch2017]
*systematic review [@Lortie2018]
*citizen science [@Burkle2013]; [@Conrad2011]
*team science [@Nielsen2017]
*R [@McCarthy2010]
*mapping [@Halpern2008]
*big data/open access databases [@Sillero2014]; [@Dengler2011]; [@Maldonado2015]
*modelling [@Vogt2018]
*surveys [@Wassen2005]
*biomonitoring [@Miguel2017]
*evolutionary change/population viability genetic analysis [@Stoops2016]
*economic incentivization monitoring [@Cerda2018]
*human health and well-being monitoring [@Mergler2007]; [@Dickman2014]
This list could potentially be expanded upon, and new tools can result in new solutions. 

**9. Explain the role that the primary tool addressed for the challenge--i.e. identification/research evidence, management/solution applied, or inform policy.**
Continuing from principle 8, this principle focuses on which tool used in a study is primarily responsible for producing results.  A good place to start may be the tile, as often a tool will be highlighted; for example, "Odonata (Insecta) as a tool for the bio-monitoring of environmental quality" [@Miguel2017].  After identifying which tool is primary, consider the role that tool could play in finding the solution to the challenge.  Three examples of roles a tool could play are:
*identification/research evidence* which seeks to better our understanding of systems so that we may more effectively manage them.   It is the most "pure" role of tools in basic science, and is also the most common in typical ecology papers.  Tools that could play this role include surveys, meta analysis, team science, systematic review, citizen science, R, mapping, open access databases, modelling.
*management/solution applied* which observes the effectiveness of management strategies.  Tools that could play this role include bio-monitoring and evolutionary change/population viability genetic analysis. 
*inform policy* which seeks to help legislators make decisions about environmental challenges.   They often take the form of anthropocentric studies that consider ecological or environmental policy.  Any tool could play this role, but some tools which fit most neatly into this role include economic incentivization monitoring and human health and well-being monitoring.
Depending on how a tool is used, these tools may play multiple roles in a solution, or may play an entirely different role than described. Most importantly, the primary tool's role informs the direction our solution should take, based on our challenge study. 

**10. Apply the tool to another challenge or explain how it is general and scaleable.**
Finally, use the primary tool explored in principle 9 to broaden the applicability of the challenge's solution.  This principle ties together the idea that reverse-engineered reproducible solutions are relevant to more than just the environmental management challenge case unpacked.   After doing all this work, it makes sense to seek and understand its reproducibility for future work!   Beyond efficiency, it also addresses the key challenge we are trying to address through these principles: Basic science can be more applicable than it sometimes appears. 

# Implications

At its core, our 10 principles for reverse-engineering solutions to solve environmental challenges are guidelines to improve science communication.  Usually, when we talk about sci comm, the burden of effective communication is on the researcher or advocate (because usually we are directing our sci comm at general audiences who are not obligated to give the researcher their attention).  But in animal behavior, communication requires at least two parties: a *sender* and a *reciever*.  In this instance, the researcher is a sender and the manager is the receiver.  For this communication to be successful, both parties must actively participate in this reuse of solutions from one domain to another.  Luckily, both parties in our scenario have incentive to engage with effective communication.   Professional advocacy is a common priority for ecologists, who hope their work influences better decision-making of both indirect and direct impactors.  And managers, of course, wish to improve their project outcomes.  Increased consumption of scientific evidence by managers, and basic science that is more palatable to a broader audience written by researchers, will result in *functional use of scientific literature*. Overall, better collaboration will encourage the realization of the common goal: solving an environmental management challenge.  



# References {#references .unnumbered}
