---
title: Simple principles for engineering reproducible solutions to environmental management challenges.
preprint: true
author: na

affiliation:

  
  
abstract: >
  An environmental management challenge is an opportunity to use fundamental science to inform evidence-based decisions for  environmental stakeholders and conservationists.  Contemporary science is embracing open science and increasingly conscious of reproduciblility.  Synergistically, applying these two paradigms in concert advances our capacity to move beyond context dependency and singlular thinking to reverse engineer solutions from published scientific evidence associated with one challenge to many. Herein, we provide a short list of principles that can guide those that seek solutions to address environmental management through primary scientific literature.
header-includes: >
  \usepackage{lipsum}
bibliography: bibliography.bib
output: 
  rticles::peerj_article:
    base_format: rmarkdown::pdf_document # bookdown::pdf_document2 # for using \@ref()


---


# Introduction {-}

Conservation decisions can reside with legislators or with environmental managers.  To focus on the latter, managers typically have scientific backgrounds and routinely navigate the technical literature.  However, engagement with scientific literature is non-trivial for all practitioners because of time, access, relevance of the science, and reporting standards.  Environmental managers and conservationists need to be able to use evidence to inform decisions [@Koontz2018;@Cash2003]. However, there can be a gap in communication between basic science and management for at least three reasons.  Firstly, the research is not a direct study of an ecosystem, and an immediate, real-world solution is needed by managers - preferably with a demonstrable outcome and reasonable cost estimate [@Iacona2018;@Naidoo2006].  This is a very real limitation in the primary science literature restoration ecology for instance [@Lortie2018]. Secondly, the link between the biology or ecology present in the literature is not articulately connected to the similar process for the system at hand. There are notable examples with journals just as the Journal of Applied Ecology, Basic and Applied Ecology, the Journal of Environmental Engineering, and many others. Nonetheless, there remains a vast pool of opportunity for solution development from publications in other journals.  Context-specific findings in science are a legitimate and useful means to advance discovery, but at times, studies from one system can be re-purposed for insights into another. Finally, the capacity to see the forest for the trees for even large-scale or broad basic research study can be a challenge. Science can be very specialized [@Baron2010], and mobilizing knowledge for solutions requires both detailed expertise, scientific synthesis tools [@Lortie2014], or a focus on identifying the salient elements associated with a study [@Lewinsohn2014;@Hao2018]. Often, seeing the forest also requires sampling many trees. This leads to the general proposal here that experts can promote reproducible and mobile knowledge for many fundamental scientific endeavors by considering these principles. This is both a set of principles for how to make your research potentially reusable by environmental managers and conservationists [@Gerstner2017] and inform solutions for the environmental crisis.


An environmental management challenge is a problem presented in scientific literature or society that, when redefined and reviewed using these principles, can result in a solution to the original problem. Typically, a challenge is ethical, legal, social, or derived from implications associated with research and evidence of change or anthropogenic stress [@Acocella2015]. Grand challenges for the environment in particular are ones that necessitate connections between disciplines and require evidence from potential studies that examine different components of the environment such as climate, ecology, species biology, or research from any number of levels [@Macpherson2017]. A (reverse-engineered) reproducible solution is a suggested solution to a challenge derived from identifying all the components of the challenge.  In software engineering, this process includes analysis of the architecture of a system, examining the relationships between subsystems, and creating a mental model of how the system functions [@Fiutem1996]. The same process can be applied to basic science as a system for supporting environmental management decisions.  It should be applicable to multiple local-extent challenges when adjusted to fit the circumstances (like a software application that can run under different operating systems). Finally, a tool or solution is the desired outcome from the primary research to support evidence-based decision making in conservation. In this case, a tool is a methodology researchers use that can facilitate managers to either identify best ways to measure/identify issues or to provide solutions for their specific challenge.  Any tool is linked to its respective reproducible solution by the fundamental concepts of reproducibility [@Baker2016]. These can include primarily conceptual replication, i.e. repeating the ideas, but there are many other solutions. Here, we propose that both direct replication (replicating the same approach in another context) and conceptual replication (repeated tests of the same concept but with different methods) [@Kelly2006] will advance our capacity to explore reproducibility of basic science to different challenges associated with environmental management. The primary goal is to escape the 'everything is context-specific' assumption sometimes applied to many natural science sub-disciplines.

The heuristic developed here was inspired by the 'ten simple rules' paper format pioneered by Phillip Bourne in the field of computational biology [@Bourne2006]. We propose that by distilling the concepts that promote engagement with scientific literature outside of the research community, managers can rely on broader sources of scientific knowledge to make decisions.  Additionally, researchers can better understand the perspective of managers facilitating science and scientific communication that is more relevant to managers without compromising their research respective programs.  Here, we will outline and discuss simple "principles" scientists can use to make their research more applicable to managers and that managers can in turn use to identify basic science that fits their needs.

# The principles {-}  


**1. Reframe the problem as challenge.**
Doom-and-gloom is a pervasive theme in the reporting and social media discussions of ecology and environmental sciences that can reduce our productivity and capacity to solve problems.  It can shut down even the most motivated of minds -- but beyond the issue of motivation, reframing a problem as a *challenge* can reveal solution sets that otherwise remain hidden.  For example, consider the problem of human-wildlife conflict between carnivores and the people living near the Ruaha National Park boundary in Tanzania.  The *problem* is that 98.5% of people perceive wildlife as a threat to their livestock resulting in increased likelihood for human-wildlife conflict [@Dickman2014].  Re-framed, the challenge can be to improve perception of wildlife in areas with high human-wildlife conflict opportunities.  It is a small change in semantics but a potentially profound change in direction. The challenge can also include improving experiences for people with wildlife or reducing their losses to wildlife.  

**2. Describe the scope and extent of the challenge.**
Defining the scope of a challenge conceptually and the extent geographically will ensure that potential solutions fit the challenge. Moving across scales is a common issue in ecology [@Sandel2015], and proposing a spatial scale, using common terms, and describing the breadth of the challenge will accelerate interdisciplinary solutions (i.e. the wildlife-human challenge above is ecological and societal).  The challenge can be problematic on local, regional, or global scales, and solutions can be needed for each.  Conceptually, the scope is broad in the human-wildlife conflict example whilst the extent is primarily local to the area surrounding the Southern border of the Ruaha National Park. Articulating scope and scale informs assessment of severity.

**3. Explicitly link the basic science to management implications and policy.**
Perhaps the most facile principle, a simple description and definition of the basic scientific evidence in a study and how it can be reused is a fundamental step in linking science to evidence-based decision making for environmental challenges. In the wildlife-human challenge, depredation of livestock impacted 61.1% of households in some form, but livestock losses due to disease or theft were actually the most consistent negative drivers of total loss [@Dickman2014].  Perception of loss and actual losses were not necessarily equivalent, and culture was shaping subsequent conflicts not direct evidence. Consequently, a clear statement of evidence can illuminate the most viable solution sets in some instances.  

**4. Propose implications of ignoring this challenge.**
A description of the impact a challenge on a system if left unchecked will help clarify the severity of the challenge. The trickle down effects and indirect implications of the challenge should also be examined. For instance, anti-carnivore sentiment will likely only grow as climate change and pressures to confine pastoral herders makes livestock more difficult to raise [@Jones2009; @Lindsey2009].  Many large carnivores are already threatened and endangered, and further anthropogenic pressures on the populations will lead to severe declines in populations including potential extinction of keystone species [@Towns2009; @Bagchi2006; @Johnson2006]; but it is often associated with underlying human-human conflict [@Dickman2010]. 

**5. State the direct human needs associated with this challenge.**
State the direct needs of humans as part of the process of generating reproducible solutions for environmental challenges.  The intrinsic value of the ecosystem is impossible to quantify [@Davidson2013], but linking the challenge and its solutions to direct human needs makes it less likely to be dismissed.  Identifying  anthropogenic needs will help a problem solver create a solution that is appropriate for the challenge, and it can also prevent the emergence of new related challenges or pressures on the system in question. This principle can also include engagement with stakeholders as a mechanism to inform benefits and solutions [@Reed2008;@Colvin2016].


**6. List at least one limitation of the study and explain.**
There is no perfect experiment [@Ruxton2017] or synthesis [@Kotiaho2002]. Critically reading the study associated with the challenge can mean the difference between success and failure of a later implemented management solution that otherwise follows all other principles presented here.  A clear analysis of causation and correlation can help avoid a fatal misstep and ensures effective framing of expected outcomes with an environmental intervention for conservationists.  This is not to say that interventions need always be cause-effect studies or that evidence-based decisions cannot be made with compelling preliminary evidence or mensurative data. We are simply proposing that a statement of the relative strength of evidence and gaps in the research provides a future direction for additional research and for implementation.  

**7. Explore the benefits of minimal intervention for stakeholders.**
Resources are limiting, and at times, the business-as-usual model can provide a guide to intervention for some environmental management challenges [@Ferguson2015;@Mosnier2017]. At the minimum, exploration of a hope-for-the-best strategy or minimal intervention is critical because of costs.  Business-as-usual models can also provide an economic mechanism to value ecosystems services [@Fu2018;@Karttunen2018], and whilst this is not without debate, this can expand the breadth of stakeholders and potential investors in a solution for a particular challenge. A best and worst case scenario analysis is also likely a frequent need for many environmental challenges because of inertia in the socio-political structures that we use to manage people and resources.

**8. List the tools applied to this challenge.**
In an environmental management challenge case study, there is typically at least one primary tool that the researchers used to explore a challenge, but there are many tools such as meta-analyses [@Busch2017], big data [@Hampton2013], mapping [@Halpern2008], modelling [@Vogt2018], citizen science [@Burkle2013], and team science [@Nielsen2017]. The tools in basic biology and ecology relevant to environmental management can be reproducible if, at least conceptually, they can be replicated in another system or applied to similar challenge -- i.e. citizen science as a means to collect environmental data [@McKinley2017] is relevant to many of the challenges we face including global warming, water quality, and declining biodiversity.

**9. Link the primary reproducible tool to the outcome.**
A reproducible science tool can provide a means to collect data, detect patterns, directly solve an environmental challenge, or inform policy. If the paper was a direct test of basic ecology for an environmental challenge, this can be very straightforward. For instance, the paper entitled 
 "Odonata (Insecta) as a tool for the bio-monitoring of environmental quality" [@Miguel2017] clearly provides a means to measure and detect.  However, the other proposed roles can address challenges in a diversity of ways. The identification of or provision of research evidence is the most 'basic' role, and it is also likely the most typical role for much of ecology for example.  Tools that can function in this capacity include surveys, citizen science data collection, mapping, open-access data, and modelling to predict changes. Tests in the second category that directly examine the efficacy of a management strategy or intervention can further include bio-monitoring [@Miguel2017], mitigation and remediation experiments [@Zhu2010], and population demography studies [@Botero2015]. Studies that inform policy are typically more indirect and synthetic and can take the form of anthropocentric studies that consider ecological or environmental policy.  Any of the above tools can serve this role, but some tools that fit most squarely include economic incentivization models (@Tilman2018), human health impact studies [@Chiabai2018], and human well-being monitoring associated with environmental interventions [@McKinnon2015].

**10. Apply the tool to another challenge or explain how it is generalizable.**
This principle proposes that the primary tool is reproducible if it can be applied to another challenge or context. It ties together the concept that reverse-engineered reproducible solutions are relevant to more than the unpacked, single environmental management challenge case. This can promote increased in efficiency for tackling novel environmental challenges as they emerge, and it also supports the overarching philosophy here for basic science that we cannot continue to ignore reuse given the global environmental needs for better decision making. 

# Implications {-}

These principles can distribute the burden of scientific communication between scientists and stakeholders and embodies a spirit of dialog between senders and receivers (or between producers and consumers). This heuristic can also enable adaptive management for the environmental sciences. The philosophy behind adaptive management is that managing and learning should be connected and iterative for decisioning for natural resources [@Williams2016]. Decision making adjusts as understanding improves both through doing and through learning. This is not a new approach to managing the environment but requires a well articulated framework to be an active process for stakeholders and to improve long-term conservation outcomes [@McDonald2010]. Making the research literature more functional through these principles will accelerate the learning phase of adaptive management. We can make deliberation (i.e. planning) and iteration (i.e. testing) integrate with evidence by adopting these principles [@Williams2016]. Reuse is also not the sole criterion for useful science nor should it be, but professional advocacy and knowledge mobilization are increasingly important priorities for universities and science in general [@Pace2010]. Evidence-based decision making is a critical area for growth and knowledge in many disciplines [@Roy-Byrne2010;@Tranfield2003;@Aarons2011] -- not just environmental management. Increased consumption of scientific evidence by managers and practitioners that is more palatable to a broader audience written by researchers will result in increased functional use of scientific literature. Collaboration with stakeholders will facilitate this process, and open science will be pivotal to adaptive management opportunities. Using at least some of these principles in the discussion sections of the primary research we report will increase the stickiness of our ideas and enable better connections between evidence and outcome, challenge and solution, and people and nature.

# References
